### ISSUE TITLE
用命令添加词库

### ISSUE THREAD

**Issue by MoKeNeng** [Special-Week/nonebot_plugin_smart_reply#13]
能不能就像教学一样，我在QQ里输入我说xxx你回答xxx，这样就可以让群友用爱产生词库而不用自己苦逼找文案。然后转发给管理员审核，审核通过就添加进去并回复那个人成功通过审核，不通过就回复不行啥的。QAQ

**Comment by Special-Week** [comment]
好难, 不会

**Comment by MoKeNeng** [comment]
好吧QaQ，谢谢
