### ISSUE TITLE
戳一戳 aac文件问题

### ISSUE THREAD

**Issue by Wexevou** [Special-Week/nonebot_plugin_smart_reply#22]
好像不能转换语音发出来 是什么原因?
![HRQQ~468OJ~QVJOT`@@B}FW](https://user-images.githubusercontent.com/117566653/227733985-45fe6c2a-c7a0-4407-8d1c-1c3cbb1eea25.png)

**Comment by Special-Week** [comment]
确保配置好了ffmpeg

**Comment by Wexevou** [comment]
啊这 你的文档没说要配置这个环境

**Comment by Special-Week** [comment]
![image](https://user-images.githubusercontent.com/87489040/227734193-603330ed-9c59-463a-bb8a-fbd7f6729047.png)

**Comment by Wexevou** [comment]
好叭 我的问题

**Comment by Wexevou** [comment]
有没有教程如何配置这个？

**Comment by Special-Week** [comment]
![L(M(HXWHH2HEKS IGJ%EH6Q](https://user-images.githubusercontent.com/87489040/227734275-4209719c-a8b3-404b-9c18-60ba0e8ae941.png)
![E86D$ UHGG%KN3O56IH5)}W](https://user-images.githubusercontent.com/87489040/227734278-c1030ef0-1f36-4b72-a6de-7dd75c661ef7.png)

https://github.com/BtbN/FFmpeg-Builds/releases

**Comment by Wexevou** [comment]
好的 谢谢

**Comment by Wexevou** [comment]
我配置好了吖
还是不行哎

**Comment by Wexevou** [comment]
![图片](https://user-images.githubusercontent.com/117566653/227755313-46414481-2ed4-4842-897a-44f067a63797.png)

**Comment by Wexevou** [comment]
![图片](https://user-images.githubusercontent.com/117566653/227755326-a32efc92-9512-43b2-83b6-f06dde11f678.png)

**Comment by Special-Week** [comment]
重启

**Comment by Wexevou** [comment]
ok 好了

**Comment by Wexevou** [comment]
newbing各种方法试过没有机器人了
openai 的 没魔法进去

**Comment by Special-Week** [comment]
![image](https://user-images.githubusercontent.com/87489040/227768074-9e1c0c81-51ad-4a70-96f4-d2b92ce50cfc.png)
你自己的问题

**Comment by Special-Week** [comment]
这俩东西就是要魔法

**Comment by Wexevou** [comment]
就是没魔法啊 支援一下？

**Comment by Wexevou** [comment]
给个群呗好聊些

**Comment by Special-Week** [comment]
你自己想办法, 我帮不了你
