### ISSUE TITLE
打不开资源

### ISSUE THREAD

**Issue by MIt-gancm** [Special-Week/nonebot_plugin_smart_reply#23]
cannot open resource
![Screenshot_20230401_105754](https://user-images.githubusercontent.com/72749591/229262594-98e38085-4fd2-4877-855b-cfeda8eae9d0.jpg)
求解

**Comment by Special-Week** [comment]
这个是输出图片的形式发送的, 我猜测你的Linux没有simsun.ttc(宋体)这个字体
解决方案: 源码内txtToImg.py中函数txt_to_img第三个参数font_path的值, 换成你系统有的字体, 或者安装simsun.ttc这个字体

**Comment by MIt-gancm** [comment]
ok了谢谢佬
