### ISSUE TITLE
安装问题求解...摸索十二小时没进展

### ISSUE THREAD

**Issue by Rulinye** [Special-Week/nonebot_plugin_smart_reply#26]
我是这两天才入坑的nonebot，然后都是通过nb安装和使用的机器人，但是我不知道该怎么安装作者你这个插件.....我通过nb install那一行安装在我的bot目录后有三个问题：1.代理我不知道配在哪里，语法是什么  2.戳一戳机器人，发送音频文件时直接发送的一串代码....   3.询问查看所有关键词没反应，控制台报错，发送openai也没反应但没报错，你好有反应。。。。现在快凌晨三点，从午休起来琢磨到现在，不知道是哪里出了问题，求作者大大解答T T

图1是戳一戳发送的代码
图2是查看所有关键词报错
<img width="345" alt="image" src="https://user-images.githubusercontent.com/129613278/234364445-0ab1eaed-cac7-4c03-8a40-2194cf9381e6.png">

<img width="659" alt="image" src="https://user-images.githubusercontent.com/129613278/234363671-b74e2cbb-f6e6-4eed-abac-2f1cc888543c.png">

**Comment by Rulinye** [comment]
哦对了，我是MacOS M1Pro

**Comment by Special-Week** [comment]
第一个报错你可能没装ffmpeg, 第二个报错是你电脑没有宋体这个字体. 
我readme应该写清楚了的
![image](https://user-images.githubusercontent.com/87489040/235639730-402c1200-e4ff-40fa-9859-8cc78c45bf14.png)

发送openai也没反应你env有设置command_start吗, bing和openai的响应器是由on_command生成的, 如果没有设置, 默认是["/"],  也就是你需要"/bing xxx"来相应, 如果想要直接bing xxx触发, 那就env设置COMMAND_START = ["/",""], 具体看https://v2.nonebot.dev/docs/api/config#Config-command_start

至于代理, 说白了就是让你命令行科学上网(openai的api调用需要梯子), macos我这里拿cfw给你举例
![image](https://user-images.githubusercontent.com/87489040/235640199-80dde0e7-a987-4aa9-bb41-caecb72b3147.png)
你这边监听了一个端口7890, 你.env应该填:
bing_or_openai_proxy = "http://127.0.0.1:1081"

**Comment by Rulinye** [comment]
非常感谢！！！
