### ISSUE TITLE
七个字的语句不使用词库

### ISSUE THREAD

**Issue by SK-Xiaohan** [Special-Week/nonebot_plugin_smart_reply#27]
在词库中，使用七字短语不会使用词库。

![QQ图片20230618215048](https://github.com/Special-Week/nonebot_plugin_smart_reply/assets/81475137/4e4f37c4-56fd-460c-9d12-9e2cb519c263)
![QQ图片20230618215056](https://github.com/Special-Week/nonebot_plugin_smart_reply/assets/81475137/2191974f-f12a-4f59-a9ef-14a197d20e00)
插件版本：现版本
noneboot2：现版本
gocq：V1.01

**Comment by Special-Week** [comment]
我觉得是被其他插件处理了, 然后他的响应器block=true, 所以这个响应器没有触发

**Comment by Special-Week** [comment]
解决方案: 请自行拉高priority(数字越大优先级越低), 以赶在被别的插件block前触发, 这个插件的响应器全放在__init__.py内, 
```python
# 普通回复响应器, 优先级999, 条件: 艾特bot就触发, block=False不会阻断事件向下传递
on_message(rule=to_me(), priority=999, block=False, handlers=[key_word_module.regular_reply])
```

**Comment by Special-Week** [comment]
稍等, 我想起来我确实有这么一个处理, 因为我的想法是文本过多适合丢给newbing或者openai处理, 毕竟这不是一个专门干词库的插件, 这个词典一开始设计来满足自己的二刺螈性癖来着, 如果你需要词库这个功能, 我推荐你使用[nonebot_plugin_word_bank2](https://github.com/kexue-z/nonebot-plugin-word-bank2), 他要比这个好用多了
```
async def get_chat_result(self, text: str, nickname: str) -> Union[str, None]:
    """从字典中返回结果"""
    if len(text) < 7:
        keys = self.anime_thesaurus.keys()
        for key in keys:
            if key in text:
                return random.choice(self.anime_thesaurus[key]).replace("你", nickname)
```

**Comment by SK-Xiaohan** [comment]
其他字数可以回复，并且我已经移除了其他插件。


感谢推荐。
