### ISSUE TITLE
这个之前的青云客api为啥不让用了呀

### ISSUE THREAD

**Issue by Eyaaaaaa** [Special-Week/nonebot_plugin_smart_reply#29]
更新了之后发现青云客的api木有了。之前还挺好用的呢【虽然是正儿八经的智障】 总比默认的智障回复强
能不能再加回去啊
ChatGPT我去年就再玩了。但是我秘钥今年4月到期了。至于那个bing那个我不知道怎么弄。也懒得配置。，我自己能访问就行。懒得弄机器人了
机器人的话主要是增添乐趣。希望作者能重新把青云客的api加到代码里面

**Comment by Special-Week** [comment]
哪有空我加回去吧, 大概没配置newbing和openai的时候就用它

**Comment by Special-Week** [comment]
我加回去了
