### ISSUE TITLE
两个优化建议

### ISSUE THREAD

**Issue by liuzj288** [Special-Week/nonebot_plugin_smart_reply#3]
1. 戳一戳回复的消息能否增加图片，音频之类
2. 回复概率能否修改，比如设置为0.5，这样更像真人

**Comment by Special-Week** [comment]
![image](https://user-images.githubusercontent.com/87489040/181296754-bd7b8876-967f-487d-8bf8-07c3608e6b19.png)
加了个戳一戳50%概率回复莲宝的藏话, 但是发送语音需要配置好ffmpeg很多设置你可以考虑自己魔改一下

**Comment by liuzj288** [comment]
> 

要增加语音是直接放进文件夹就行了么，.mp3也是直接放进去么

**Comment by Special-Week** [comment]
目前只加了.aac 需要.mp3需要多加一个判断,
![image](https://user-images.githubusercontent.com/87489040/181398139-3fcb2cfb-3f91-4af0-ad0b-5c51cf2c8ab7.png)
wan's
晚上下班回来我再加一个or吧

**Comment by Special-Week** [comment]
> > 
> 
> 要增加语音是直接放进文件夹就行了么，.mp3也是直接放进去么

已处理

**Comment by liuzj288** [comment]
> > > 
> > 
> > 
> > 要增加语音是直接放进文件夹就行了么，.mp3也是直接放进去么
> 
> 已处理

如果再放个图片文件夹是不是可以用同样逻辑实现戳一戳概率返回表情包图片

**Comment by Special-Week** [comment]
我手上暂时没有什么好玩的图片, 你想实现就照着这个随机龙图抄一抄吧
![image](https://user-images.githubusercontent.com/87489040/181580332-65258364-c624-4a86-a49f-2a109a985bf7.png)

**Comment by liuzj288** [comment]
> 我手上暂时没有什么好玩的图片, 你想实现就照着这个随机龙图抄一抄吧 ![image](https://user-images.githubusercontent.com/87489040/181580332-65258364-c624-4a86-a49f-2a109a985bf7.png)

我这样改语法哪里错了，怎么修改下好
![3abdacc600e87911538ef373900747dc](https://user-images.githubusercontent.com/13833404/181591827-86a56ec7-6107-4d3a-8f26-52f3702a8d54.png)

**Comment by Special-Week** [comment]
我想你应该这样写
![image](https://user-images.githubusercontent.com/87489040/181595643-5279121f-fb36-43fd-91f6-0515914a84b3.png)
![image](https://user-images.githubusercontent.com/87489040/181595670-88620f17-37ad-4223-ba94-d9f98e1cbe31.png)

**Comment by liuzj288** [comment]
> 我想你应该这样写 ![image](https://user-images.githubusercontent.com/87489040/181595643-5279121f-fb36-43fd-91f6-0515914a84b3.png) ![image](https://user-images.githubusercontent.com/87489040/181595670-88620f17-37ad-4223-ba94-d9f98e1cbe31.png)

确实，去查了python的if嵌套改的差不多了， 发送图片那个不需要try么

**Comment by Special-Week** [comment]
> > 我想你应该这样写 ![image](https://user-images.githubusercontent.com/87489040/181595643-5279121f-fb36-43fd-91f6-0515914a84b3.png) ![image](https://user-images.githubusercontent.com/87489040/181595670-88620f17-37ad-4223-ba94-d9f98e1cbe31.png)
> 
> 确实，去查了python的if嵌套改的差不多了， 发送图片那个不需要try么

你当然也可以进行try处理一下，有几个原因可能会发送失败，比如img文件夹放了且随机到了messagesegment.image解析不了的图片文件或者根本不是图片文件，又或者图片太色了，让tx给风控了

**Comment by liuzj288** [comment]
> > > 我想你应该这样写 ![image](https://user-images.githubusercontent.com/87489040/181595643-5279121f-fb36-43fd-91f6-0515914a84b3.png) ![image](https://user-images.githubusercontent.com/87489040/181595670-88620f17-37ad-4223-ba94-d9f98e1cbe31.png)
> > 
> > 
> > 确实，去查了python的if嵌套改的差不多了， 发送图片那个不需要try么
> 
> 你当然也可以进行try处理一下，有几个原因可能会发送失败，比如img文件夹放了且随机到了messagesegment.image解析不了的图片文件或者根本不是图片文件，又或者图片太色了，让tx给风控了

感觉还可以加个回戳，一行代码的话怎么写好，官方文档直接写的qq号

**Comment by Special-Week** [comment]
> > > > 我想你应该这样写 ![image](https://user-images.githubusercontent.com/87489040/181595643-5279121f-fb36-43fd-91f6-0515914a84b3.png) ![image](https://user-images.githubusercontent.com/87489040/181595670-88620f17-37ad-4223-ba94-d9f98e1cbe31.png)
> > > 
> > > 
> > > 确实，去查了python的if嵌套改的差不多了， 发送图片那个不需要try么
> > 
> > 
> > 你当然也可以进行try处理一下，有几个原因可能会发送失败，比如img文件夹放了且随机到了messagesegment.image解析不了的图片文件或者根本不是图片文件，又或者图片太色了，让tx给风控了
> 
> 感觉还可以加个回戳，一行代码的话怎么写好，官方文档直接写的qq号

![image](https://user-images.githubusercontent.com/87489040/181790279-ac769a20-791f-4778-9564-0e69c9757879.png)

**Comment by liuzj288** [comment]
w

> 

我这样写问题出现在哪里，怎么报错呢，麻了
![df4751625c7bdc63270e85cc610ada2f](https://user-images.githubusercontent.com/13833404/181811039-006df48c-f74f-4c5f-ba1c-50d6cd675a90.png)
![660efcabd0754e880d1f51be4d8f313a](https://user-images.githubusercontent.com/13833404/181811083-538b31b5-4d95-45fd-8840-913b07653b7c.png)
