### ISSUE TITLE
如何阻断戳一戳（

### ISSUE THREAD

**Issue by zhulinyv** [Special-Week/nonebot_plugin_smart_reply#8]
我抄了一下之前的代码，但是戳一戳还是会被响应QwQ。
`@attack.handle()`
`async def handle_receive(event: MessageEvent):`
`    img = Path(os.path.join(os.path.dirname(__file__), "resource")) / "1.jpg"`
`    qid = event.get_user_id()`
`    data = read_json()`
`    mid = event.message_id`
`    # 写入json,记录时间和id`
`    write_json(qid, event.time, mid, data)`
`    await attack.send(message=f"{random.choice(attack_sendmessage)}"+MessageSegment.image(img), at_sender=True)`

**Comment by Special-Week** [comment]
你这是想干嘛

**Comment by Special-Week** [comment]
阻断戳一戳直接在戳一戳的handle函数第一行就return呗

**Comment by zhulinyv** [comment]
> 你这是想干嘛

实现触发关键词后把用户暂时拉黑，忽略该用户所有指令，可是戳一戳仍会被响应。在第一行就return不就直接不能戳一戳了嘛...
```
import asyncio
from nonebot.exception import IgnoredException
from nonebot.plugin.on import on_keyword, on_message, on_notice, on_command
from nonebot.rule import to_me
from nonebot.message import event_preprocessor
from nonebot.params import CommandArg
from nonebot.permission import SUPERUSER
from nonebot.adapters.onebot.v11 import (
    Bot,
    GroupMessageEvent,
    Message,
    MessageEvent,
    PokeNotifyEvent,
    MessageSegment
)
from .utils import *
from loguru import logger

cdTime = 21600

attack = on_keyword(["傻逼", "sb", "SB", "你妈", "nm", "色批", "泥马", "病", "尼玛", "傻鸟", "傻狗", "狗", "儿子", "爹", "爸爸", "猪", "沙雕", "卧槽", "妈的", "傻卵", "二逼", "二臂", "爷爷", "有病", "MD"], rule=to_me(), block=True, priority=1)

remove_CD = on_command("remove_sb", permission=SUPERUSER, block=True)

ai = on_message(rule=to_me(), priority=99)

@attack.handle()
async def handle_receive(event: MessageEvent):
    img = Path(os.path.join(os.path.dirname(__file__), "resource")) / "1.jpg"
    qid = event.get_user_id()
    data = read_json()
    mid = event.message_id
    write_json(qid, event.time, mid, data)
    await attack.send(message=f"{random.choice(attack_sendmessage)}"+MessageSegment.image(img), at_sender=True)

@event_preprocessor
async def event_preblock_sb(event: MessageEvent, bot: Bot):
    if not event.get_user_id() in bot.config.superusers:
        qid = event.get_user_id()
        data = read_json()
        try:
            cd = event.time - data[qid][0]
        except Exception:
            cd = cdTime + 1
        if cd > cdTime:
            return
        blockreason = "这货骂了我家bot"
        if blockreason:
            logger.info(f'当前事件已阻断，原因：{blockreason}')
            raise IgnoredException(blockreason)

api_flag = True
api_switch = on_command("智障回复api切换", aliases={
                        "ai切换", "api_switch","智能回复api切换"}, permission=SUPERUSER, rule=to_me(), block=True)
ai = on_message(rule=to_me(), priority=99, block=False)
poke_ = on_notice(rule=to_me(), priority=99, block=False)


@api_switch.handle()
async def _():
    global api_flag
    api_flag = not api_flag
    await api_switch.send(message=f"切换成功, 当前智能回复api为{'青云客' if api_flag else '小爱同学'}")


@ai.handle()
async def _(event: MessageEvent):
    msg = str(event.get_message())
    msg = re.sub(r"\[.*?\]", "", msg)
    if (not msg) or msg.isspace() or msg in [
        "你好啊",
        "你好",
        "在吗",
        "在不在",
        "您好",
        "您好啊",
        "你好",
        "在",
    ]:
        await ai.finish(Message(random.choice(hello__reply)))
    if isinstance(event, GroupMessageEvent):
        nickname = event.sender.card or event.sender.nickname
    else:
        nickname = event.sender.nickname
    result = await get_chat_result(msg,  nickname)
    if result == None:
        if api_flag:
            qinyun_url = f"http://api.qingyunke.com/api.php?key=free&appid=0&msg={msg}"
            message = await qinyun_reply(qinyun_url)
            logger.info("来自青云客的智能回复: " + message)
        else:
            xiaoai_url = f"https://jintia.jintias.cn/api/xatx.php?msg={msg}"
            message = await xiaoice_reply(xiaoai_url)
            logger.info("来自小爱同学的智能回复: " + message)
        await ai.finish(message=message)
    await ai.finish(Message(result))


@poke_.handle()
async def _poke_event(bot: Bot,event: PokeNotifyEvent)-> bool:
    if event.is_tome:
        if random.random() < 0.2:
            message="别戳了别戳了,这张图给你了,让我安静一会儿,30秒后我要撤回\n" + MessageSegment.image(file='https://dev.iw233.cn/api.php?sort=random')
            setu_msg_id = await poke_.send(message)
            setu_msg_id = setu_msg_id['message_id']
            await asyncio.sleep(30)
            await bot.delete_msg(message_id=setu_msg_id)
            return
        elif random.random() < 0.5:
            try:
                await poke_.send(MessageSegment.record(Path(aac_file_path)/random.choice(aac_file_list)))
            except:
                await poke_.send(message=f"{random.choice(poke__reply)}")
        else:
            await poke_.send(message=f"{random.choice(poke__reply)}")

@remove_CD.handle()
async def _(msg: Message = CommandArg()):
    qid = msg.extract_plain_text()
    boolean = False
    try:
        remove_json(qid)
        boolean = True
    except:
        pass
    if boolean:
        await remove_CD.finish(f"ID:{qid}CD已清除, 下次别骂{NICKNAME}了")
    else:
        await remove_CD.finish(f"{NICKNAME}记忆里没有这号人欸")

```

**Comment by Special-Week** [comment]
那你处理起来要稍微走点弯路, 那东西好像只能抛出message事件, 如果你想抛出戳一戳事件的话, 在戳一戳handle函数里面做一个遍历操作, 判断那个人有没有被拉黑, 如果有就return

**Comment by Special-Week** [comment]
或者试一试NoneBotException中的其他抛出异常的类, 比如FinishedException等

**Comment by zhulinyv** [comment]
> 或者试一试NoneBotException中的其他抛出异常的类, 比如FinishedException等(我没用过,不清楚)
> 
> ```shell
> NoneBotException
> ├── ParserExit
> ├── ProcessException
> |   ├── IgnoredException
> |   ├── SkippedException
> |   |   └── TypeMisMatch
> |   ├── MockApiException
> |   └── StopPropagation
> ├── MatcherException
> |   ├── PausedException
> |   ├── RejectedException
> |   └── FinishedException
> ├── AdapterException
> |   ├── NoLogException
> |   ├── ApiNotAvailable
> |   ├── NetworkError
> |   └── ActionFailed
> └── DriverException
>     └── WebSocketClosed
> ```

试了 `FinishedException` 和其它一些，可是它并不能阻断戳一戳，于是我加入了这些，好像有点笨，但它起作用了QAQ。
```
    with open('./data/sb_CDusercd.json','r',encoding='utf8')as fp:
        json_data = json.load(fp)
    qid = str(event.get_user_id())
    if qid in json_data:
        return
    else:
```

**Comment by Special-Week** [comment]
> > 或者试一试NoneBotException中的其他抛出异常的类, 比如FinishedException等(我没用过,不清楚)
> > ```shell
> > NoneBotException
> > ├── ParserExit
> > ├── ProcessException
> > |   ├── IgnoredException
> > |   ├── SkippedException
> > |   |   └── TypeMisMatch
> > |   ├── MockApiException
> > |   └── StopPropagation
> > ├── MatcherException
> > |   ├── PausedException
> > |   ├── RejectedException
> > |   └── FinishedException
> > ├── AdapterException
> > |   ├── NoLogException
> > |   ├── ApiNotAvailable
> > |   ├── NetworkError
> > |   └── ActionFailed
> > └── DriverException
> >     └── WebSocketClosed
> > ```
> 
> 试了 `FinishedException` 和其它一些，可是它并不能阻断戳一戳，于是我加入了这些，好像有点笨，但它起作用了QAQ。
> 
> ```
>     with open('./data/sb_CDusercd.json','r',encoding='utf8')as fp:
>         json_data = json.load(fp)
>     qid = str(event.get_user_id())
>     if qid in json_data:
>         return
>     else:
> ```

能run就行

**Comment by Special-Week** [comment]
我忽视了一点,
@event_preprocessor
async def event_preblock_sb(event: MessageEvent, bot: Bot):
事件预处理的时候传入的是MessageEvent, 也就是消息事件, 而戳一戳是NotifyEvent, 也就是说戳一戳的时候根本没有进入这个函数, 并不是IgnoredException不能阻断戳一戳, 你把MessageEvent换成基类Event, 这样所有事件都能进入这个事件预处理函数, 而不是只有MessageEvent

**Comment by zhulinyv** [comment]
我将 `async def event_preblock_sb(event: MessageEvent, bot: Bot):`
改为了 `async def event_preblock_sb(event: Event, bot: Bot):`
确实达到了想要的效果，但是 bot 端会出现无尽的报错...
![image](https://user-images.githubusercontent.com/66541860/198932844-4bf4e721-216e-48a1-a787-1886a0bcb1b8.png)

**Comment by Special-Week** [comment]
> 我将 `async def event_preblock_sb(event: MessageEvent, bot: Bot):` 改为了 `async def event_preblock_sb(event: Event, bot: Bot):` 确实达到了想要的效果，但是 bot 端会出现无尽的报错... ![image](https://user-images.githubusercontent.com/66541860/198932844-4bf4e721-216e-48a1-a787-1886a0bcb1b8.png)

事件预处理对event因为传的messagevent等共同的基类，你操作了子类才拥有的方法，get_user_id需要换一个方法

**Comment by zhulinyv** [comment]
> 

听懂了，但不会用。 ：(

**Comment by zhulinyv** [comment]
> > 我将 `async def event_preblock_sb(event: MessageEvent, bot: Bot):` 改为了 `async def event_preblock_sb(event: Event, bot: Bot):` 确实达到了想要的效果，但是 bot 端会出现无尽的报错... ![image](https://user-images.githubusercontent.com/66541860/198932844-4bf4e721-216e-48a1-a787-1886a0bcb1b8.png)
> 
> 事件预处理对event因为传的messagevent等共同的基类，Event没对get_user_id()这个方法作出实现，可以使用if isinstance(event, MessageEvent)作出判断或者直接抛出异常

听懂了，但不会用。：(

**Comment by Special-Week** [comment]
> > > 我将 `async def event_preblock_sb(event: MessageEvent, bot: Bot):` 改为了 `async def event_preblock_sb(event: Event, bot: Bot):` 确实达到了想要的效果，但是 bot 端会出现无尽的报错... ![image](https://user-images.githubusercontent.com/66541860/198932844-4bf4e721-216e-48a1-a787-1886a0bcb1b8.png)
> > 
> > 
> > 事件预处理对event因为传的messagevent等共同的基类，Event没对get_user_id()这个方法作出实现，可以使用if isinstance(event, MessageEvent)作出判断或者直接抛出异常
> 
> 听懂了，但不会用。：(

![image](https://user-images.githubusercontent.com/87489040/198962388-b0d385db-3050-4704-abf5-2a0a5bf8817d.png)
详细的事件参考nonebot.adapters.onebot.v11.event.py

**Comment by zhulinyv** [comment]
> > > > 我将 `async def event_preblock_sb(event: MessageEvent, bot: Bot):` 改为了 `async def event_preblock_sb(event: Event, bot: Bot):` 确实达到了想要的效果，但是 bot 端会出现无尽的报错... ![image](https://user-images.githubusercontent.com/66541860/198932844-4bf4e721-216e-48a1-a787-1886a0bcb1b8.png)
> > > 
> > > 
> > > 事件预处理对event因为传的messagevent等共同的基类，Event没对get_user_id()这个方法作出实现，可以使用if isinstance(event, MessageEvent)作出判断或者直接抛出异常
> > 
> > 
> > 听懂了，但不会用。：(
> 
> ![image](https://user-images.githubusercontent.com/87489040/198962388-b0d385db-3050-4704-abf5-2a0a5bf8817d.png) 详细的事件参考nonebot.adapters.onebot.v11.event.py

阿里嘎多，已经改好了捏ヾ(≧▽≦*)o
