### ISSUE TITLE
新的 小爱同学 API

### ISSUE THREAD

**Issue by zhulinyv** [Special-Week/nonebot_plugin_smart_reply#9]
[https://apibug.cn/doc/xiaoai.html](https://apibug.cn/doc/xiaoai.html)
需要ApiKey，可以去免费注册一个。
不需要改代码，懒癌患者狂喜🤤

**Comment by Special-Week** [comment]
看到了, 这就更新代码

**Comment by Special-Week** [comment]
push完代码然后他好像寄了
![image](https://user-images.githubusercontent.com/87489040/203072101-36624a5b-1687-4e50-b6e6-638d777cc2c8.png)

**Comment by zhulinyv** [comment]
> push完代码然后他好像寄了 ![image](https://user-images.githubusercontent.com/87489040/203072101-36624a5b-1687-4e50-b6e6-638d777cc2c8.png)

寄，我甚至用了不到一个小时（😭
